#!/usr/bin/env bash

mv -f "ProgramTests.TestSeed.0000.received.txt" "ProgramTests.TestSeed.0000.approved.txt"
mv -f "ProgramTests.TestSeed.0001.received.txt" "ProgramTests.TestSeed.0001.approved.txt"
mv -f "ProgramTests.TestSeed.0002.received.txt" "ProgramTests.TestSeed.0002.approved.txt"
mv -f "ProgramTests.TestSeed.0003.received.txt" "ProgramTests.TestSeed.0003.approved.txt"
mv -f "ProgramTests.TestSeed.0004.received.txt" "ProgramTests.TestSeed.0004.approved.txt"
mv -f "ProgramTests.TestSeed.0005.received.txt" "ProgramTests.TestSeed.0005.approved.txt"
mv -f "ProgramTests.TestSeed.0006.received.txt" "ProgramTests.TestSeed.0006.approved.txt"
mv -f "ProgramTests.TestSeed.0007.received.txt" "ProgramTests.TestSeed.0007.approved.txt"
mv -f "ProgramTests.TestSeed.0008.received.txt" "ProgramTests.TestSeed.0008.approved.txt"
mv -f "ProgramTests.TestSeed.0009.received.txt" "ProgramTests.TestSeed.0009.approved.txt"
mv -f "ProgramTests.TestSeed.0010.received.txt" "ProgramTests.TestSeed.0010.approved.txt"
mv -f "ProgramTests.TestSeed.0011.received.txt" "ProgramTests.TestSeed.0011.approved.txt"
mv -f "ProgramTests.TestSeed.0012.received.txt" "ProgramTests.TestSeed.0012.approved.txt"
mv -f "ProgramTests.TestSeed.0013.received.txt" "ProgramTests.TestSeed.0013.approved.txt"
mv -f "ProgramTests.TestSeed.0014.received.txt" "ProgramTests.TestSeed.0014.approved.txt"
mv -f "ProgramTests.TestSeed.0015.received.txt" "ProgramTests.TestSeed.0015.approved.txt"
mv -f "ProgramTests.TestSeed.0016.received.txt" "ProgramTests.TestSeed.0016.approved.txt"
mv -f "ProgramTests.TestSeed.0017.received.txt" "ProgramTests.TestSeed.0017.approved.txt"
mv -f "ProgramTests.TestSeed.0018.received.txt" "ProgramTests.TestSeed.0018.approved.txt"
mv -f "ProgramTests.TestSeed.0019.received.txt" "ProgramTests.TestSeed.0019.approved.txt"
